/*
 * programmer_bootloader_frames.h
 *
 *  Created on: Apr 25, 2023
 *      Author: richa
 */

#ifndef INC_PROGRAMMER_BOOTLOADER_FRAMES_H_
#define INC_PROGRAMMER_BOOTLOADER_FRAMES_H_

#define PROG_GO_TO_BL_DATA_0 222
#define PROG_GO_TO_BL_DATA_1 79
#define PROG_GO_TO_BL_DATA_2 182
#define PROG_GO_TO_BL_DATA_3 205
#define PROG_GO_TO_BL_DATA_4 146
#define PROG_GO_TO_BL_DATA_5 49
#define PROG_GO_TO_BL_DATA_6 238
#define PROG_GO_TO_BL_DATA_7 35

#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_0 197
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_1 208
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_2 163
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_3 186
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_4 237
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_5 107
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_6 175
#define BL_WAITING_FOR_ACKNOWLEDGEMENT_DATA_7 211

#define BL_WAITING_FOR_FRAMECOUNT_DATA_0 97
#define BL_WAITING_FOR_FRAMECOUNT_DATA_1 108
#define BL_WAITING_FOR_FRAMECOUNT_DATA_2 242
#define BL_WAITING_FOR_FRAMECOUNT_DATA_3 111
#define BL_WAITING_FOR_FRAMECOUNT_DATA_4 194
#define BL_WAITING_FOR_FRAMECOUNT_DATA_5 236
#define BL_WAITING_FOR_FRAMECOUNT_DATA_6 222
#define BL_WAITING_FOR_FRAMECOUNT_DATA_7 149

#define BL_WAITING_FOR_CRC_DATA_0 12
#define BL_WAITING_FOR_CRC_DATA_1 6
#define BL_WAITING_FOR_CRC_DATA_2 138
#define BL_WAITING_FOR_CRC_DATA_3 235
#define BL_WAITING_FOR_CRC_DATA_4 116
#define BL_WAITING_FOR_CRC_DATA_5 214
#define BL_WAITING_FOR_CRC_DATA_6 225
#define BL_WAITING_FOR_CRC_DATA_7 150

#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_0 78
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_1 176
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_2 228
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_3 68
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_4 204
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_5 172
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_6 89
#define BL_WAITING_FOR_CHUNK_RESYNC_DATA_7 60

#endif /* INC_PROGRAMMER_BOOTLOADER_FRAMES_H_ */
